using System.Text.Json;

namespace JPVOS.Services.Outbound;

public sealed class JsonlOutboundReceiptStore : IOutboundReceiptStore
{
    private readonly string _path; private readonly string _eventsPath; private readonly SemaphoreSlim _gate = new(1,1); private readonly JsonSerializerOptions _json=new(JsonSerializerDefaults.Web);
    public JsonlOutboundReceiptStore(string path){_path=path;_eventsPath=path+".events";var directory=Path.GetDirectoryName(path);if(!string.IsNullOrWhiteSpace(directory))Directory.CreateDirectory(directory);}
    public async Task SaveAsync(OutboundMessageReceipt receipt,CancellationToken ct){await _gate.WaitAsync(ct);try{var all=await ReadAllUnsafeAsync(ct);all[receipt.MessageId]=receipt;await RewriteUnsafeAsync(all.Values,ct);}finally{_gate.Release();}}
    public async Task<OutboundMessageReceipt?> GetAsync(string id,CancellationToken ct){await _gate.WaitAsync(ct);try{return(await ReadAllUnsafeAsync(ct)).GetValueOrDefault(id);}finally{_gate.Release();}}
    public async Task<OutboundMessageReceipt?> FindByProviderMessageIdAsync(string id,CancellationToken ct){await _gate.WaitAsync(ct);try{return(await ReadAllUnsafeAsync(ct)).Values.FirstOrDefault(x=>x.ProviderMessageId==id);}finally{_gate.Release();}}
    public async Task<OutboundMessageReceipt?> FindLatestForPrincipalAsync(string id,CancellationToken ct){await _gate.WaitAsync(ct);try{return(await ReadAllUnsafeAsync(ct)).Values.Where(x=>x.TargetPrincipalId==id).OrderByDescending(x=>x.AdmittedAtUtc).FirstOrDefault();}finally{_gate.Release();}}
    public async Task<OutboundMessageReceipt?> FindByAcknowledgmentCodeAsync(string principal,string code,CancellationToken ct){await _gate.WaitAsync(ct);try{return(await ReadAllUnsafeAsync(ct)).Values.FirstOrDefault(x=>x.TargetPrincipalId==principal&&string.Equals(x.AcknowledgmentCode,code,StringComparison.OrdinalIgnoreCase));}finally{_gate.Release();}}
    public async Task<bool> TryMarkProviderEventProcessedAsync(string eventId,CancellationToken ct){if(string.IsNullOrWhiteSpace(eventId))return false;await _gate.WaitAsync(ct);try{var existing=File.Exists(_eventsPath)?new HashSet<string>((await File.ReadAllLinesAsync(_eventsPath,ct)).Where(x=>!string.IsNullOrWhiteSpace(x)),StringComparer.Ordinal):new HashSet<string>(StringComparer.Ordinal);if(!existing.Add(eventId))return false;var temp=_eventsPath+".tmp";await File.WriteAllLinesAsync(temp,existing.OrderBy(x=>x),ct);File.Move(temp,_eventsPath,true);return true;}finally{_gate.Release();}}
    public async Task<OutboundMessageReceipt?> ApplyAcknowledgmentAsync(string principal,string code,string providerId,DateTimeOffset now,CancellationToken ct){await _gate.WaitAsync(ct);try{var all=await ReadAllUnsafeAsync(ct);var receipt=all.Values.FirstOrDefault(x=>x.TargetPrincipalId==principal&&string.Equals(x.AcknowledgmentCode,code,StringComparison.OrdinalIgnoreCase));if(receipt is null)return null;if(receipt.State==OutboundMessageState.Acknowledged)return receipt;var updated=receipt with{State=OutboundMessageState.Acknowledged,AcknowledgedAtUtc=now,AcknowledgmentEvidenceType="attributable_inbound_sms",AcknowledgmentEvidenceReference=providerId};all[updated.MessageId]=updated;await RewriteUnsafeAsync(all.Values,ct);return updated;}finally{_gate.Release();}}
    public async Task<ProviderStatusApplyResult> ApplyProviderStatusAsync(string providerId,string eventId,OutboundMessageState next,DateTimeOffset now,CancellationToken ct){await _gate.WaitAsync(ct);try{var all=await ReadAllUnsafeAsync(ct);var receipt=all.Values.FirstOrDefault(x=>x.ProviderMessageId==providerId);if(receipt is null)return new(ProviderStatusApplyDisposition.NotFound);var processed=new HashSet<string>(receipt.ProcessedProviderEventIds??Array.Empty<string>(),StringComparer.Ordinal);if(!processed.Add(eventId))return new(ProviderStatusApplyDisposition.Duplicate,receipt);if(receipt.State==OutboundMessageState.Acknowledged||(receipt.State==OutboundMessageState.Delivered&&next==OutboundMessageState.Failed)||(Rank(next)<Rank(receipt.State)&&next!=OutboundMessageState.Failed))return new(ProviderStatusApplyDisposition.Ignored,receipt);var sentAt=(next is OutboundMessageState.Sent or OutboundMessageState.Delivered)&&receipt.SentAtUtc is null?now:receipt.SentAtUtc;var updated=receipt with{State=next,SentAtUtc=sentAt,DeliveredAtUtc=next==OutboundMessageState.Delivered?now:receipt.DeliveredAtUtc,FailedAtUtc=next==OutboundMessageState.Failed?now:receipt.FailedAtUtc,ProcessedProviderEventIds=processed.OrderBy(x=>x).ToArray()};all[updated.MessageId]=updated;await RewriteUnsafeAsync(all.Values,ct);return new(ProviderStatusApplyDisposition.Updated,updated);}finally{_gate.Release();}}
    private async Task<Dictionary<string,OutboundMessageReceipt>> ReadAllUnsafeAsync(CancellationToken ct){var result=new Dictionary<string,OutboundMessageReceipt>(StringComparer.Ordinal);if(!File.Exists(_path))return result;foreach(var line in(await File.ReadAllLinesAsync(_path,ct)).Where(x=>!string.IsNullOrWhiteSpace(x))){var receipt=JsonSerializer.Deserialize<OutboundMessageReceipt>(line,_json);if(receipt is not null)result[receipt.MessageId]=receipt;}return result;}
    private async Task RewriteUnsafeAsync(IEnumerable<OutboundMessageReceipt> receipts,CancellationToken ct){var temp=_path+".tmp";await File.WriteAllLinesAsync(temp,receipts.OrderBy(x=>x.AdmittedAtUtc).Select(x=>JsonSerializer.Serialize(x,_json)),ct);File.Move(temp,_path,true);}
    private static int Rank(OutboundMessageState state)=>state switch{OutboundMessageState.Queued=>0,OutboundMessageState.Sent=>1,OutboundMessageState.Delivered=>2,OutboundMessageState.Failed=>3,OutboundMessageState.Acknowledged=>4,_=>0};
}
