name: deploy-appservice

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore ./src/JPVOS/JPVOS.csproj

      - name: Build
        run: dotnet build ./src/JPVOS/JPVOS.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/JPVOS/JPVOS.csproj -c Release -o ./publish

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: jpv-os-access-gateway
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
