name: Release Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-web:
    name: Publish ASP.NET Core Web App
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'


      - name: Restore
        run: dotnet restore src/JPVOS/JPVOS.csproj

      - name: Build
        run: dotnet build src/JPVOS/JPVOS.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish src/JPVOS/JPVOS.csproj -c Release -o publish --no-build

      - name: Upload release artifact
        uses: actions/upload-artifact@v7
        with:
          name: jpvos-release
          path: publish
